#!/usr/bin/perl

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 1, or (at your option)
# any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

my $EGGDROPDIR = "/home/eggdrop/eggdrop";

my $Command = $ARGV[0];
if ($Command eq "")
{
	$Command = "NONE";
}

my $running=`ps ax|grep eggdrop|grep -v grep`;

if ($Command eq "start")
{
	if ($running eq "")
	{
		print "Starting Eggdrop...\n";
		if (-f "$EGGDROPDIR/nostart")
		{
			print "Removing $EGGDROPDIR/nostart\n";
			# Remove the lock file if it exists
			unlink("$EGGDROPDIR/nostart");
		}
		# Start the screen process
		system("nohup $EGGDROPDIR/starteggdrop > /tmp/EggdropStartup.log\&");
	}
}
elsif ($Command eq "stop")
{
	print "Stopping Eggdrop process...\n";
	system("touch '$EGGDROPDIR/nostart'");
	if ($running ne "")
	{
		# Process is running, kill it
		system("killall eggdrop");
	}
}
elsif ($Command eq "restart")
{
	if (-f "$EGGDROPDIR/nostart")
	{
		print("Removing $EGGDROPDIR/nostart\n");
		unlink("$EGGDROPDIR/nostart");
	}
	if ($running ne "")
	{
		system("killall eggdrop");
	}
}
elsif ($Command eq "status")
{
	if ($running ne "")
	{
		print("Eggdrop Server Running\n");
	}
	else
	{
		print("Eggdrop Server Not Running\n");
	}
}
else
{
	print ("Uknown command '$Command'\n");
	print ("Usage: $0 {start|status|stop|restart}\n");
	exit(1);
}

exit(0);
